package src

import (
	"bytes"
	"compress/gzip"
	"fmt"
	"io/fs"
	"mime"
	"net/http"
	"path/filepath"
	"strconv"
	"strings"

	"github.com/andybalholm/brotli"
)

// compressedAsset holds one embedded asset's content type plus its original
// bytes and, when compression actually shrinks the file, precomputed gzip
// and brotli variants. Static assets are fixed at compile time (the assets
// and dist embed.FS vars in serve.go), so compressing them once at package
// init — rather than per request or as a separate build step — avoids
// repeated CPU work without adding build tooling, matching the fail-fast,
// parse-once pattern terminalTemplate uses for the embedded HTML templates.
type compressedAsset struct {
	contentType string
	original    []byte
	gzip        []byte // nil when gzip didn't shrink the file
	brotli      []byte // nil when brotli didn't shrink the file
}

// extraContentTypes fills in extensions mime.TypeByExtension does not
// resolve to a useful type. Go's built-in mime table has no entry for .ico.
var extraContentTypes = map[string]string{
	".ico": "image/x-icon",
}

// contentTypeFor determines the Content-Type for an asset the same way
// http.FileServer does: by extension first, falling back to sniffing the
// content when the extension is unrecognized.
func contentTypeFor(name string, content []byte) string {
	ext := filepath.Ext(name)
	if ct, ok := extraContentTypes[ext]; ok {
		return ct
	}
	if ct := mime.TypeByExtension(ext); ct != "" {
		return ct
	}
	return http.DetectContentType(content)
}

// compressBytes gzip- and brotli-compresses data, returning nil for either
// variant that doesn't end up smaller than the original — never worth
// serving a "compressed" payload that's bigger than the source (this can
// happen for very small or already-compressed files).
func compressBytes(data []byte) (gzipped, brotlied []byte) {
	var gzBuf bytes.Buffer
	gw := gzip.NewWriter(&gzBuf)
	_, _ = gw.Write(data)
	_ = gw.Close()
	if gzBuf.Len() < len(data) {
		gzipped = gzBuf.Bytes()
	}

	var brBuf bytes.Buffer
	bw := brotli.NewWriter(&brBuf)
	_, _ = bw.Write(data)
	_ = bw.Close()
	if brBuf.Len() < len(data) {
		brotlied = brBuf.Bytes()
	}

	return gzipped, brotlied
}

// buildCompressedAssets walks fsys and returns a map from the request path
// (as the mux sees it, e.g. "assets/terminal.min.js") to its precomputed
// compressedAsset.
func buildCompressedAssets(fsys fs.FS) (map[string]compressedAsset, error) {
	result := make(map[string]compressedAsset)
	err := fs.WalkDir(fsys, ".", func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if d.IsDir() {
			return nil
		}
		content, err := fs.ReadFile(fsys, path)
		if err != nil {
			return fmt.Errorf("read %s: %w", path, err)
		}
		gz, br := compressBytes(content)
		result[path] = compressedAsset{
			contentType: contentTypeFor(path, content),
			original:    content,
			gzip:        gz,
			brotli:      br,
		}
		return nil
	})
	if err != nil {
		return nil, err
	}
	return result, nil
}

// mustBuildCompressedAssets panics if fsys cannot be walked, matching the
// fail-fast pattern template.Must uses for other embedded, compile-time-known
// assets (see terminalTemplate in display_handler.go) — a failure here can
// only mean the embed itself is broken, which should never happen at runtime.
func mustBuildCompressedAssets(fsys fs.FS) map[string]compressedAsset {
	result, err := buildCompressedAssets(fsys)
	if err != nil {
		panic(fmt.Sprintf("build compressed assets: %v", err))
	}
	return result
}

// compressedAssets holds every file embedded via the assets embed.FS
// (serve.go — hand-authored static files like favicon.ico and terminal.css),
// pre-compressed with gzip and brotli at package init. Served at /assets/.
var compressedAssets = mustBuildCompressedAssets(assets)

// compressedDistAssets holds every file embedded via the dist embed.FS
// (serve.go — bun's bundled/code-split client build output, generated by
// `make client`), pre-compressed the same way. Served at /dist/.
var compressedDistAssets = mustBuildCompressedAssets(dist)

// newAssetsHandler returns an http.Handler serving files from assetMap,
// negotiating gzip or brotli encoding from the request's Accept-Encoding
// header (brotli preferred when the client accepts both) and falling back to
// the uncompressed original for clients that support neither, or for files
// compression didn't shrink. Unlike http.FileServer this does not support
// Range requests or conditional GETs (If-Modified-Since/ETag) — acceptable
// here since these are small, rarely-changing build artifacts rather than
// large media files.
func newAssetsHandler(assetMap map[string]compressedAsset) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Method != http.MethodGet && r.Method != http.MethodHead {
			w.WriteHeader(http.StatusMethodNotAllowed)
			return
		}

		path := strings.TrimPrefix(r.URL.Path, "/")
		asset, ok := assetMap[path]
		if !ok {
			http.NotFound(w, r)
			return
		}

		body := asset.original
		encoding := ""
		acceptEncoding := r.Header.Get("Accept-Encoding")
		if asset.brotli != nil && strings.Contains(acceptEncoding, "br") {
			body = asset.brotli
			encoding = "br"
		} else if asset.gzip != nil && strings.Contains(acceptEncoding, "gzip") {
			body = asset.gzip
			encoding = "gzip"
		}

		w.Header().Set("Content-Type", asset.contentType)
		w.Header().Set("Vary", "Accept-Encoding")
		if encoding != "" {
			w.Header().Set("Content-Encoding", encoding)
		}
		w.Header().Set("Content-Length", strconv.Itoa(len(body)))
		if r.Method == http.MethodHead {
			return
		}
		_, _ = w.Write(body)
	}
}

// assetsHandler serves compressedAssets (src/assets/) at /assets/.
var assetsHandler = newAssetsHandler(compressedAssets)

// distHandler serves compressedDistAssets (src/dist/) at /dist/.
var distHandler = newAssetsHandler(compressedDistAssets)
