package src

const DEFAULT_TITLE = "b3tty"
const DEFAULT_ROOT = "/"
const DEFAULT_WORKING_DIRECTORY = "$HOME"
const DEFAULT_SHELL = "$SHELL"
const DEFAULT_URI = "localhost"
const DEFAULT_ROWS = 24
const DEFAULT_COLS = 0
const DEFAULT_FONT_FAMILY = "na"
const DEFAULT_FONT_SIZE = 14
const DEFAULT_CURSOR_BLINK = true
const DEFAULT_PROFILE_NAME = "default"
const BUFFER_SIZE = 4096
const MAX_REQUEST_BODY_SIZE = 4096
const TOKEN_LENGTH = 24
